use role sysadmin;  

USE ROLE SYSADMIN;
USE WAREHOUSE ACCOUNT_ADMIN_WH;

CREATE DATABASE IF NOT EXISTS DBT_DEMO;
CREATE SCHEMA IF NOT EXISTS DBT_DEMO.ADMIN_CONFIG WITH MANAGED ACCESS;

 
 
CREATE  OR REPLACE SECRET  DBT_DEMO.ADMIN_CONFIG.GM_PS_GITHUB_SECRET
  TYPE = PASSWORD
  USERNAME = 'sfc-gh-gmalige'
  PASSWORD = '#######'
 COMMENT = 'connection to my priviate gitlab' ;  

 

show SECRETS IN SCHEMA  DBT_DEMO.ADMIN_CONFIG;

 
 
CREATE OR REPLACE API INTEGRATION GM_API_DBT_DEMO_GITHUB_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-gmalige')
  ALLOWED_AUTHENTICATION_SECRETS = (DBT_DEMO.ADMIN_CONFIG.GM_PS_GITHUB_SECRET) 
   ENABLED = TRUE;
 

  CREATE OR REPLACE GIT REPOSITORY GM_DBT_PROJECTS_DEMO_GITHUB_REPO
  API_INTEGRATION = GM_API_DBT_DEMO_GITHUB_INTEGRATION
  ORIGIN = 'https://github.com/sfc-gh-gmalige/gm_dbt_projects_demo.git'
 GIT_CREDENTIALS = DBT_DEMO.ADMIN_CONFIG.GM_PS_GITHUB_SECRET
;   

 


   show dbt projects;

   GRANT APPLICATION ROLE SNOWFLAKE.EVENTS_ADMIN TO ROLE sysadmin;

GRANT APPLICATION ROLE SNOWFLAKE.EVENTS_VIEWER TO ROLE sysadmin;